// svelte/src/App.svelte
<script>
import logo from './assets/svelte.png'
import {
    Router,
    Route,
    useNavigate
} from 'svelte-navigator'
import Todolist from './lib/Todolist.svelte';
import Todo from './lib/Todo.svelte';

function handleNavigation() {
    window.location.href = "/"
}
</script>

<Router>
    <div class="img-wrapper" style="width: 100%;">
        <img src={logo} on:click={handleNavigation} id="homelink" alt="svelte logo">
    </div>
    <div>
        <Route path="/" component={Todolist} />
        <!-- CANNOT UNDERSTAND WHAT PRIMARY DOES -->
        <Route path="/todo/:id" component={Todo} primary={false}/>
    </div>
</Router>

// react/src/App.jsx
import TodoList from "./views/TodoList";
import Todo from "./views/Todo";
import { BrowserRouter as Router, Routes, Route, Link } from "react-router-dom";
import logo from "./logo.svg";

function App() {
    return (
        <Router>
            <div className="App">
                <Link to="/">
                    <div className="img-wrapper">
                        <img
                            src={logo}
                            alt="react logo"
                            style={{ height: "100%" }}
                        />
                    </div>
                </Link>
            </div>
            <Routes>
                <Route path="/" element={<TodoList />} />
                <Route path="/todo/:id" element={<Todo />} />
            </Routes>
        </Router>
    );
}

export default App;
