// svelte/src/lib/Todolist.svelte
<script>
import plus from "../../../plus.png"
import todoService from "../../../todo-service"

export let location;
export let navigate;

function goToTodo(id) {
    navigate(`/todo/${id}`)
}
</script>

<div>
    <h1 class="title">TODO list
        <img src={plus} alt="plus symbol">
    </h1>
    <div class="todo-container">
        {#await todoService.getTodos() then todos}
        <ul>
            {#each todos as todo}
            <li on:click={() => goToTodo(todo._id)}>
                <div class={todo.state ? "todo done-true" : "todo done-false"}>
                    <div class="todo-content">
                        <div>by <h3 class="author">{todo.author}</h3></div>
                        <h4>{todo.content}</h4>
                    </div>
                </div>
            </li>
            {/each}
        </ul>

        {/await}

    </div>
</div>

// react/src/views/TodoList.jsx
import todoService from "../../../todo-service";
import plus from "../../../plus.png";
import React from "react";
import { useState } from "react";
import { useNavigate } from "react-router-dom";

export default function TodoList() {
    const navigate = useNavigate();
    const [todos, setTodos] = useState([]);
    todoService.getTodos().then((todos) => setTodos(todos));

    return (
        <div>
            <h1 className="title">
                TODO list&nbsp;
                <img
                    src={plus}
                    alt="plus symbol"
                    onClick={() => navigate("/create")}
                />
            </h1>
            <div className="todo-container">
                <ul>
                    {todos.map((todo, i) => {
                        return (
                            <li
                                key={i}
                                onClick={() => {
                                    navigate(`/todo/${todo._id}`);
                                }}
                            >
                                <div
                                    className={
                                        todo.state
                                            ? "todo done-true"
                                            : "todo done-false"
                                    }
                                >
                                    <div className="todo-content">
                                        <div>
                                            by&nbsp;
                                            <h3 className="author">
                                                {todo.author}
                                            </h3>
                                        </div>
                                        <h4>{todo.content}</h4>
                                    </div>
                                </div>
                            </li>
                        );
                    })}
                </ul>
            </div>
        </div>
    );
}
